server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workout_tracker
    username: workout_user
    password: workout_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: 67566B59703373367639792F423F4528482B4D6251655468576D5A7134743777
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.workout.tracker: DEBUG